== Et là je les utilise ?

=== !

[%step]
[source, java]
----
...
if (optional.isPresent()) {
    var value = optional.get();
// NOOOOOOOOOOOOOOOOON !!!!
}
...
----

[.notes]
--
Code vu en vrai...
Ici soit on a a main sur la méthode `app.getCodeImputationDefaut()`,
Sinon je ne suis pas certain qu'on est gagné quoique ce soit, particulièrement en terme de lisibilité

A ce moment là autant continuer à travailler avec du null
--

=== !

[%step]
--
[source,java]
----
String code = Optional.ofNullable(app.getCodeImputationDefaut())
                .orElse(Strings.EMPTY);
----
--

[.notes]
--
Ici soit on est sur une représentation du monde exterieur et c'est à la méthode getCodeImputationDefaut de renvoyer une valeur par défaut...
--

=== !

[%step]
--
[source,java]
----
String value = Optional.ofNullable(monService.getValue())
                .orElse(null);
----
--

[.notes]
--
Je raccourci 2 appels trouvés dans du code.

A ce moment là autant continuer à travailler avec du null, ou faire un vrai exercice de refacto pour ne plus utiliser null!
--


=== Optional<List>


icon:poop[4*,role=red]

[.notes]
--
Et plus généralement, de tout ce qui ressemble à une collection.
--

=== Cas à la marge

[.notes]
--
Il existe en effet des cas ou la nullité n'a pas le même sens que l'absence, dans ce cas...

Plus globalement, tout ce que j'ai raconté correspond à du cas général, mais on trouvera TOUJOURS des contre-exemples...
--